// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7sjlIMYCXdnuLU0C7xnMfBmwFneCZLLY',
    appId: '1:152066728128:web:980f1fdd953357fb5a0d25',
    messagingSenderId: '152066728128',
    projectId: 'coffeeapp-951f0',
    authDomain: 'coffeeapp-951f0.firebaseapp.com',
    storageBucket: 'coffeeapp-951f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHBCnreJ1X3Z-R8huHvQCreLUsT-RvEIA',
    appId: '1:152066728128:android:eec70191907585735a0d25',
    messagingSenderId: '152066728128',
    projectId: 'coffeeapp-951f0',
    storageBucket: 'coffeeapp-951f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59a-qO2ZHsygUIY6FO8v3huDZsYH9CN4',
    appId: '1:152066728128:ios:7cc669585298dd155a0d25',
    messagingSenderId: '152066728128',
    projectId: 'coffeeapp-951f0',
    storageBucket: 'coffeeapp-951f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59a-qO2ZHsygUIY6FO8v3huDZsYH9CN4',
    appId: '1:152066728128:ios:7cc669585298dd155a0d25',
    messagingSenderId: '152066728128',
    projectId: 'coffeeapp-951f0',
    storageBucket: 'coffeeapp-951f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7sjlIMYCXdnuLU0C7xnMfBmwFneCZLLY',
    appId: '1:152066728128:web:a3fe5e42d6f1589b5a0d25',
    messagingSenderId: '152066728128',
    projectId: 'coffeeapp-951f0',
    authDomain: 'coffeeapp-951f0.firebaseapp.com',
    storageBucket: 'coffeeapp-951f0.firebasestorage.app',
  );
}
